In [5]:
import requests
import xlsxwriter
import pandas as pd
import numpy as np
import yfinance as yf
import yahoo_fin.stock_info as si 
from yahoo_fin import *
import datetime as dt
from pandas_datareader import data as pdr 
from datetime import datetime, timedelta

In [6]:
# created a csv file of ticker symbols for an excel database
nasdaq = pd.DataFrame(si.tickers_nasdaq())
sym = set( symbol for symbol in nasdaq[0].values.tolist() )

# deleting the inactive tickers by suffix
my_list = ['C', 'W', 'T', 'R', 'P', 'Q', 'Z', 'I', '.A']

# variable for tickers to be saved and disgarded
del_set = set()
sav_set = set()

# loop to id the suffix and disgard
for symbol in sym:
    if len( symbol ) > 4 and symbol[-1] in my_list:
        del_set.add( symbol )
    else:
        sav_set.add( symbol )
        
tickers = sorted(sav_set)

In [8]:
yf.pdr_override

# Calculate the date range
end = dt.datetime.today().strftime('%Y-%m-%d')
begin = (dt.datetime.today() - dt.timedelta(days=30)).strftime('%Y-%m-%d')

# Create an empty DataFrame to store the stock prices
prices = pd.DataFrame()

# Iterate through each stock ticker
for stock in tickers:
    try:
        # Download the Adj Close data for each stock
        stock_data = yf.download(stock, start=begin, end=end, progress=False)

        # Check if the DataFrame is empty (no data downloaded)
        if not stock_data.empty:
            # Rename the 'Adj Close' column to the stock ticker
            stock_data.rename(columns={'Adj Close': stock}, inplace=True)

            # Concatenate the stock data to the prices DataFrame
            if prices.empty:
                prices = stock_data[[stock]]
            else:
                prices = pd.concat([prices, stock_data[[stock]]], axis=1)
        else:
            print(f"No data available for {stock}.")
    except Exception as e:
        print(f"An error occurred while fetching {stock}: {str(e)}")

# Display the updated prices DataFrame w/o null values
prices.dropna()
prices

1 Failed download:
['THAR']: Exception("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")

No data available for THAR.

1 Failed download:
['YHGJ']: Exception("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")

No data available for YHGJ.

1 Failed download:
['ZXYZ.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

No data available for ZXYZ.A.

,AACG,AACI,AACIU,AADI,AADR,AAL,AAME,AAOI,AAON,AAPB,...,ZNTL,ZS,ZTEK,ZUMZ,ZURA,ZVRA,ZVSA,ZYME,ZYNE,ZYXI
Date,,,,,,,,,,,,,,,,,,,,,
2023-08-28,1.21,10.61,10.65,6.800,52.000000,14.73,2.10,12.970,60.705490,25.350000,...,25.620001,141.339996,1.40,17.660000,6.730,5.110,0.149,7.49,1.32,7.66
2023-08-29,1.24,10.61,10.65,6.710,52.610001,14.90,2.12,14.100,62.683060,26.260000,...,25.590000,144.389999,1.40,18.280001,6.790,5.310,0.143,7.53,1.32,7.71
2023-08-30,1.26,10.53,10.65,6.680,52.580002,14.77,1.96,15.220,62.703037,27.200001,...,26.580000,147.279999,1.42,18.150000,6.910,5.300,0.142,7.35,1.32,7.75
2023-08-31,1.24,10.53,10.65,6.300,52.189999,14.73,2.03,13.770,62.982697,27.230000,...,26.559999,156.050003,1.39,18.990000,6.880,5.070,0.142,7.24,1.33,7.70
2023-09-01,1.26,10.54,10.65,5.860,52.160000,14.68,1.98,13.940,65.579514,27.540001,...,27.139999,158.380005,1.37,18.830000,6.980,5.380,0.141,7.49,1.32,7.55
2023-09-05,1.23,10.74,10.65,5.490,51.610001,14.30,1.95,12.950,64.261124,27.650000,...,25.420000,162.740005,1.36,18.230000,6.870,5.030,0.129,7.33,1.33,7.09
2023-09-06,1.21,10.74,10.65,5.320,51.580002,14.33,1.88,12.450,65.180000,25.879999,...,25.290001,158.350006,1.37,18.709999,6.970,4.980,0.131,7.20,1.32,6.95
2023-09-07,1.19,10.74,10.65,5.220,50.860001,14.00,1.86,12.320,65.699997,24.559999,...,25.040001,161.020004,1.35,18.660000,6.600,5.270,0.123,6.96,1.32,7.12
2023-09-08,1.18,10.74,10.65,5.130,50.380001,13.98,1.90,11.800,65.570000,24.690001,...,25.280001,160.770004,1.35,16.760000,6.140,5.260,0.126,7.12,1.32,7.39
2023-09-11,1.12,10.75,10.65,5.645,50.830002,14.09,1.96,11.650,64.730003,25.000000,...,24.950001,165.050003,1.35,17.450001,6.730,5.420,0.111,7.00,1.33,8.00
2023-09-12,1.16,10.75,10.65,5.960,50.500000,14.11,1.88,11.360,62.939999,24.250000,...,24.700001,160.220001,1.31,16.480000,7.030,5.395,0.129,6.87,1.32,8.10
2023-09-13,1.16,10.75,10.65,6.050,50.410000,13.31,1.95,9.120,61.230000,23.709999,...,24.250000,158.399994,1.30,16.440001,6.960,5.060,0.190,6.85,1.33,8.09
2023-09-14,1.14,10.75,10.65,5.930,50.779999,13.26,1.95,9.755,60.939999,24.080000,...,23.790001,159.229996,1.24,17.139999,6.880,5.120,0.150,6.78,1.35,8.60
2023-09-15,1.13,10.75,10.65,5.540,50.439999,13.31,1.99,9.840,60.880001,23.879999,...,23.410000,156.100006,1.28,16.580000,6.060,5.130,0.149,6.80,1.39,8.29
2023-09-18,1.13,10.70,10.65,5.360,50.790001,13.11,1.94,9.880,60.869999,24.620001,...,22.490000,154.720001,1.30,16.480000,6.185,5.090,0.132,6.79,1.33,8.04
2023-09-19,1.13,10.70,10.65,5.380,50.369999,13.19,1.92,9.640,61.770000,24.860001,...,22.170000,155.050003,1.29,16.950001,5.750,5.090,0.136,6.90,1.33,8.23
2023-09-20,1.16,10.70,10.65,5.240,50.369999,13.06,1.96,9.840,61.220001,23.940001,...,22.520000,154.229996,1.28,17.670000,6.010,4.940,0.132,6.64,1.35,8.03
2023-09-21,1.14,10.70,10.65,5.190,49.419998,13.06,1.94,9.310,56.680000,23.590000,...,22.139999,148.789993,1.28,17.270000,6.150,4.990,0.130,6.46,1.34,8.37
2023-09-22,1.14,10.70,10.65,4.990,49.490002,12.90,1.95,9.580,56.950001,23.799999,...,21.270000,151.710007,1.26,17.410000,6.400,4.860,0.133,6.40,1.34,8.43